stretch_gripper_controller:
  ros__parameters:
    joints:
      - joint_gripper_finger_right
      - joint_gripper_finger_left
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_gripper_finger_right: {trajectory: 0.1, goal: 0.1}
      joint_gripper_finger_left: {trajectory: 0.1, goal: 0.1}
      stop_trajectory_duration: 0.5
