stretch_head_controller:
  ros__parameters:
    joints:
      - joint_head_pan
      - joint_head_tilt
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_head_pan: {trajectory: 0.1, goal: 0.1}
      joint_head_tilt: {trajectory: 0.1, goal: 0.1}
      stop_trajectory_duration: 0.5