controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    stretch_mobile_base_controller:
      type: diff_drive_controller/DiffDriveController
    
    stretch_arm_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
    
    stretch_head_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

stretch_mobile_base_controller:
  ros__parameters:

    publish_rate: 50.0

    left_wheel_names: [joint_left_wheel]
    right_wheel_names: [joint_right_wheel]

    wheel_separation: 0.315
    wheel_radius: 0.05

    # Odometry covariances for the encoder output of the robot. These values should
    # be tuned to your robot's sample odometry data, but these values are a good place
    # to start
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

    # Top level frame (link) of the robot description
    base_frame_id: base_link

    use_stamped_vel: false

    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.2              # m/s
        min_velocity: -0.2             # m/s
        has_acceleration_limits: true
        max_acceleration: 0.6          # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0              # rad/s
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 6.0          # rad/s^2
        min_acceleration: -1.0

stretch_head_controller:
  ros__parameters:
    joints:
      - joint_head_pan
      - joint_head_tilt
    command_interfaces:
      - position
    state_interfaces:
      - position
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_head_pan: {trajectory: 0.1, goal: 0.1}
      joint_head_tilt: {trajectory: 0.1, goal: 0.1}
      stop_trajectory_duration: 0.5

stretch_arm_controller:
  ros__parameters:
    joints:
      - joint_lift
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      stop_trajectory_duration: 0.5
      joint_lift:
        goal: 0.1
        trajectory: 0.1

# stretch_arm_controller:
#   ros__parameters:
#       joints:
#         - joint_lift
#       command_interfaces:
#         - position
#       state_interfaces:
#         - position

#       state_publish_rate: 200.0 # Defaults to 50
#       action_monitor_rate: 20.0 # Defaults to 20

#       allow_partial_joints_goal: false # Defaults to false
#       open_loop_control: true
#       allow_integration_in_goal_trajectories: true
#       constraints:
#         stopped_velocity_tolerance: 0.05 # Defaults to 0.01
#         goal_time: 0.6 # Defaults to 0.0 (start immediately)